[package]
name = "proofly"
version = "0.1.0"
description = "Proofly AI-verified escrow with attestation-based fund release"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "proofly"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
